name: cd ping

on:
  push:
    tags:
      - '*'

jobs:
  ping:
    permissions:
      contents: write
    strategy:
      matrix:
        repo:
          - toolbox
          - vulkan.zig
          - wayland.zig
          - X11.zig
          - glfw.zig
          - cimgui.zig
          - spirv.zig
          - glslang.zig
          - shaderc.zig
          - oniguruma.zig
    runs-on: ubuntu-latest
    steps:
    - uses: tiawl/spaceporn-action-cd-ping@v1.1.0
      with:
        from: "${{ github.event.repository.name }}"
        is_composite: 'true'
        to: "${{ matrix.repo }}"
        tag: "${{ github.ref_name }}"
        token: "${{ secrets.PAT }}"
